### ISSUE TITLE
woocommerce_rest_shop_webhook_invalid_topic 

### ISSUE THREAD

**Issue by kamhawy4** [Codexshaper/laravel-woocommerce#81]
display error when i use Webhook (order create) 

and this is my code 

<img width="787" alt="Screen Shot 2021-12-25 at 1 53 53 AM" src="https://user-images.githubusercontent.com/25951080/147374462-67acf4d2-0ccb-4a64-9f03-213b8b15afb1.png">

and t
<img width="1115" alt="Screen Shot 2021-12-25 at 1 56 29 AM" src="https://user-images.githubusercontent.com/25951080/147374463-7d5bd1cb-bcc6-4848-92a3-ed480d458c0f.png">

and this is error

Exception: Error: موضوع الـ Webhook مطلوباً ويجب أن يكون صالحاً. [woocommerce_rest_shop_webhook_invalid_topic] in file /home2/shosaaxieexpress/public_html/vendor/codexshaper/laravel-woocommerce/src/Traits/WooCommerceTrait.php on line 63

#0 /home2/shosaaxieexpress/public_html/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(261): Codexshaper\WooCommerce\WooCommerceApi->create('webhooks', Array)
#1 /home2/shosaaxieexpress/public_html/vendor/codexshaper/laravel-woocommerce/src/Traits/QueryBuilderTrait.php(95): Illuminate\Support\Facades\Facade::__callStatic('create', Array)
#2 /home2/shosaaxieexpress/public_html/vendor/codexshaper/laravel-woocommerce/src/Models/BaseModel.php(45): Codexshaper\WooCommerce\Models\Webhook->create(Array)
#3 /home2/shosaaxieexpress/public_html/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(261): Codexshaper\WooCommerce\Models\BaseModel->__call('create', Array)
#4 /home2/shosaaxieexpress/public_html/app/Http/Controllers/api/WoocommerceController.php(129): Illuminate\Support\Facades\Facade::__callStatic('create', Array)
#5 /home2/shosaaxieexpress/public_html/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): App\Http\Controllers\api\WoocommerceController->order_create(Object(Illuminate\Http\Request))
#6 /home2/shosaaxieexpress/public_html/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\Routing\Controller->callAction('order_create', Array)
#7 /home2/shosaaxieexpress/public_html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(254): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(App\Http\Controllers\api\WoocommerceController), 'order_create')
#8 /home2/shosaaxieexpress/public_html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(197): Illuminate\Routing\Route->runController()
#9 /home2/shosaaxieexpress/public_html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(693): Illuminate\Routing\Route->run()
#10 /home2/shosaaxieexpress/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#11 /home2/shosaaxieexpress/public_html/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#12 /home2/shosaaxieexpress/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Routing\Middleware\SubstituteBindings->handle(Object(Illuminate\Http\Request), Object(Closure))
#13 /home2/shosaaxieexpress/public_html/vendor/laravel/framework/src/Illuminate/Routing/Middleware/ThrottleRequests.php(127): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#14 /home2/shosaaxieexpress/public_html/vendor/laravel/framework/src/Illuminate/Routing/Middleware/ThrottleRequests.php(103): Illuminate\Routing\Middleware\ThrottleRequests->handleRequest(Object(Illuminate\Http\Request), Object(Closure), Array)
#15 /home2/shosaaxieexpress/public_html/vendor/laravel/framework/src/Illuminate/Routing/Middleware/ThrottleRequests.php(55): Illuminate\Routing\Middleware\ThrottleRequests->handleRequestUsingNamedLimiter(Object(Illuminate\Http\Request), Object(Closure), 'api', Object(Closure))
#16 /home2/shosaaxieexpress/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Routing\Middleware\ThrottleRequests->handle(Object(Illuminate\Http\Request), Object(Closure), 'api')
#17 /home2/shosaaxieexpress/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#18 /home2/shosaaxieexpress/public_html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(695): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#19 /home2/shosaaxieexpress/public_html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(670): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#20 /home2/shosaaxieexpress/public_html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(636): Illuminate\Routing\Router->runRoute(Object(Illuminate\Http\Request), Object(Illuminate\Routing\Route))
#21 /home2/shosaaxieexpress/public_html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(625): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#22 /home2/shosaaxieexpress/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(166): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#23 /home2/shosaaxieexpress/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#24 /home2/shosaaxieexpress/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#25 /home2/shosaaxieexpress/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle(Object(Illuminate\Http\Request), Object(Closure))
#26 /home2/shosaaxieexpress/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#27 /home2/shosaaxieexpress/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle(Object(Illuminate\Http\Request), Object(Closure))
#28 /home2/shosaaxieexpress/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#29 /home2/shosaaxieexpress/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Foundation\Http\Middleware\ValidatePostSize->handle(Object(Illuminate\Http\Request), Object(Closure))
#30 /home2/shosaaxieexpress/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#31 /home2/shosaaxieexpress/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Foundation\Http\Middleware\PreventRequestsDuringMaintenance->handle(Object(Illuminate\Http\Request), Object(Closure))
#32 /home2/shosaaxieexpress/public_html/vendor/fruitcake/laravel-cors/src/HandleCors.php(57): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#33 /home2/shosaaxieexpress/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fruitcake\Cors\HandleCors->handle(Object(Illuminate\Http\Request), Object(Closure))
#34 /home2/shosaaxieexpress/public_html/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#35 /home2/shosaaxieexpress/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fideloper\Proxy\TrustProxies->handle(Object(Illuminate\Http\Request), Object(Closure))
#36 /home2/shosaaxieexpress/public_html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#37 /home2/shosaaxieexpress/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(141): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#38 /home2/shosaaxieexpress/public_html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(110): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#39 /home2/shosaaxieexpress/public_html/public/index.php(52): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#40 {main}

**Comment by maab16** [comment]
Hello @kamhawy4,

Thanks for creating the issue. I reviewed your code and It seems your code is okay. You can make sure some settings

Follow below links

https://woocommerce.com/document/webhooks/
https://woocommerce.github.io/woocommerce-rest-api-docs/?php#create-a-webhook

```
use Codexshaper\WooCommerce\Facades\WooCommerce;

$data = [
    'name' => 'Order updated',
    'topic' => 'order.updated',
    'delivery_url' => 'http://requestb.in/1g0sxmo1'
];
print_r(WooCommerce::create('webhooks', $data));
```

If you believe you setup everything perfectly but it still not working let me know. If you need paid support you can mail me `maab.career@gmail.com`.

Thanks
